import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
const baseURL=process.env.FOLIO_TEST_URL || 'http://localhost:5173';
const browser=await chromium.launch({headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1100},colorScheme:'light'});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto(baseURL);
await page.getByRole('heading',{name:'Small details. Better interfaces.'}).waitFor();
assert.equal(await page.locator('.component-card').count(),12);
await page.getByRole('button',{name:'Inputs',exact:true}).click();
assert.equal(await page.locator('.component-card').count(),5);
await page.getByRole('button',{name:'All components',exact:true}).click();
await page.getByRole('textbox',{name:'Search components'}).fill('switch');
assert.equal(await page.locator('.component-card').count(),1);
await page.getByRole('textbox',{name:'Search components'}).fill('');
await page.getByText('Marketing emails',{exact:true}).click();
assert.equal(await page.getByRole('switch',{name:'Marketing emails'}).isChecked(),true);
await page.getByRole('button',{name:'Create project',exact:true}).click();
await page.getByPlaceholder('My next big idea').fill('Browser smoke test');
await page.getByRole('dialog').getByRole('button',{name:'Create project',exact:true}).click();
await page.getByRole('status').waitFor();
await page.locator('.component-caption').first().click();
await page.getByRole('dialog').getByRole('heading',{name:'Button',exact:true}).waitFor();
await page.keyboard.press('Escape');
const lightBackground=await page.locator('.component-card').first().evaluate(el=>getComputedStyle(el).backgroundColor);
await page.getByRole('button',{name:'Toggle color theme'}).click();
await page.waitForFunction(()=>document.documentElement.dataset.mode==='dark');
const darkBackground=await page.locator('.component-card').first().evaluate(el=>getComputedStyle(el).backgroundColor);
assert.notEqual(darkBackground,lightBackground);
assert.equal(await page.locator('.app').evaluate(el=>getComputedStyle(el).filter),'none');
await page.locator('.component-caption').first().click();
assert.equal(await page.locator('.modal').evaluate(el=>getComputedStyle(el).backgroundColor),darkBackground,'Portaled modal must inherit the dark surface');
await page.keyboard.press('Escape');
await page.screenshot({path:'/tmp/folio-dark.png',fullPage:true});
await page.getByRole('button',{name:'Toggle color theme'}).click();
await page.waitForFunction(()=>document.documentElement.dataset.mode==='light');
await page.screenshot({path:'/tmp/folio-preview.png',fullPage:true});
await page.locator('nav').getByRole('button',{name:'Theming',exact:true}).click();
assert.equal(await page.locator('.token-chip').count(),54);
await page.locator('nav').getByRole('button',{name:'Components',exact:false}).click();
await page.setViewportSize({width:390,height:844});
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
await page.getByRole('button',{name:'Open navigation'}).click();
await page.locator('nav').getByRole('button',{name:'Blocks'}).click();
await page.getByRole('heading',{name:'A running start.'}).waitFor();
await page.screenshot({path:'/tmp/folio-mobile.png',fullPage:true});
const registry=await (await page.request.get(`${baseURL}/r/folio.json`)).json();
assert.equal(registry.type,'registry:ui');assert.ok(registry.files[0].content.includes('react-aria-components'));
assert.deepEqual(errors,[]);
console.log('PASS: catalog, filters, switches, dialogs, mobile layout, navigation, registry, light/dark tokens, portal theming, and no runtime errors');
await browser.close();
