'use client';
import { Button as AriaButton, Switch as AriaSwitch, Checkbox as AriaCheckbox, TextField, Label, Input, type ButtonProps, type SwitchProps, type CheckboxProps } from 'react-aria-components';
import { Check } from 'lucide-react';
import { clsx } from 'clsx';
import { twMerge } from 'tailwind-merge';
export function Button({className,variant='secondary',...props}:ButtonProps & {variant?:'primary'|'secondary'|'ghost'}) { return <AriaButton {...props} className={twMerge(clsx('inline-flex items-center justify-center gap-2 rounded-md px-3 py-2 text-sm font-medium cursor-pointer outline-none focus-visible:ring-2 focus-visible:ring-kumo-focus disabled:opacity-40 disabled:cursor-not-allowed',variant==='primary'?'bg-kumo-brand text-folio-on-brand hover:bg-kumo-brand-hover':variant==='ghost'?'hover:bg-kumo-tint':'bg-kumo-control text-kumo-default ring-1 ring-kumo-line hover:bg-kumo-fill-hover',className))}/> }
export function Switch(props:SwitchProps) { return <AriaSwitch {...props} className="group flex items-center gap-3 text-sm cursor-pointer"><span className="flex h-5 w-9 shrink-0 items-center rounded-full bg-kumo-interact px-0.5 group-data-[selected]:bg-kumo-brand group-data-[focus-visible]:ring-2 ring-kumo-focus"><span className="h-4 w-4 rounded-full bg-folio-on-brand shadow-sm group-data-[selected]:translate-x-4"/></span>{props.children as React.ReactNode}</AriaSwitch> }
export function Checkbox(props:CheckboxProps) { return <AriaCheckbox {...props} className="group flex items-center gap-2.5 text-sm cursor-pointer"><span className="flex size-4 items-center justify-center rounded bg-kumo-control ring-1 ring-kumo-line group-data-[selected]:bg-kumo-brand group-data-[selected]:ring-kumo-brand group-data-[focus-visible]:ring-2"><Check size={12} className="text-folio-on-brand opacity-0 group-data-[selected]:opacity-100"/></span>{props.children as React.ReactNode}</AriaCheckbox> }
export function Field({label,placeholder,type='text'}:{label:string;placeholder?:string;type?:string}) {return <TextField className="flex flex-col gap-1.5 text-sm" type={type}><Label className="font-medium">{label}</Label><Input placeholder={placeholder} className="w-full rounded-md bg-kumo-control px-3 py-2 text-sm text-kumo-default placeholder:text-kumo-placeholder ring-1 ring-kumo-line outline-none focus:ring-2 focus:ring-kumo-focus"/></TextField>}
