import { readFile, writeFile } from "node:fs/promises";
// Kumo token reference, https://kumo-ui.com/colors/ (2026-10-02).
// Primitive var() references are resolved to Tailwind v4 values where available.
export const tokens = JSON.parse(
  await readFile(
    new URL("../registry/styles/tokens.json", import.meta.url),
    "utf8",
  ),
);
export const theme = Object.fromEntries(
  Object.entries(tokens).map(([name, [light, dark]]) => [
    name,
    light === dark ? light : `light-dark(${light}, ${dark})`,
  ]),
);
// Primary controls keep white foregrounds in both modes; inverse text is for contrast surfaces.
theme["--color-folio-on-brand"] = "#fff";
theme["--color-folio-backdrop"] = "oklch(0% 0 0 / 0.4)";
Object.assign(
  theme,
  JSON.parse(
    await readFile(
      new URL("../registry/styles/surfaces.json", import.meta.url),
      "utf8",
    ),
  ),
);
export const css = {
  "@theme static": theme,
  ":root": { "color-scheme": "light dark" },
  '[data-mode="light"]': { "color-scheme": "light" },
  '[data-mode="dark"]': { "color-scheme": "dark" },
};
await writeFile(
  new URL("../registry/styles/tokens.css", import.meta.url),
  "/* Generated by scripts/theme.mjs from tokens.json. Do not edit directly. */\n" +
    Object.entries(css)
      .map(
        ([selector, declarations]) =>
          `${selector} {\n${Object.entries(declarations)
            .map(([name, value]) => `  ${name}: ${value};`)
            .join("\n")}\n}`,
      )
      .join("\n\n") +
    "\n",
);

// The CLI accepts theme declarations through cssVars, not css["@theme static"].
// Root declarations preserve variables referenced by gradients/shadows at runtime.
export const registryCssVars = { theme };
export const registryCss = Object.fromEntries(
  Object.entries(css).filter(([selector]) => !selector.startsWith("@theme")),
);
registryCss[":root"] = { ...theme, "color-scheme": "light dark" };
