export const catalog = [
  {
    slug: "alert",
    name: "Alert",
    category: "Feedback",
    description: "Communicate an important status or result.",
    api: null,
    exports: ["Alert"],
    props: [
      {
        name: "title",
        type: "string",
        description: "Alert heading.",
      },
      {
        name: "variant",
        type: "success | warning | danger | info",
        description: "Semantic appearance.",
      },
    ],
    alpha: false,
  },
  {
    slug: "autocomplete",
    name: "Autocomplete",
    category: "Collections",
    description: "Filter a collection as you type.",
    api: "Autocomplete",
    exports: ["SearchField", "Input", "ListBox", "ListBoxItem"],
    props: [
      {
        name: "filter",
        type: "(textValue, inputValue) => boolean",
        description: "Filter the child collection.",
      },
      {
        name: "inputValue / defaultInputValue",
        type: "string",
        description: "Controlled or initial search query.",
      },
    ],
    alpha: false,
  },
  {
    slug: "avatar",
    name: "Avatar",
    category: "Layout & files",
    description: "Represent a person with their initials.",
    api: null,
    exports: ["Avatar"],
    props: [
      {
        name: "name",
        type: "string",
        description: "Accessible name and initials.",
      },
    ],
    alpha: false,
  },
  {
    slug: "badge",
    name: "Badge",
    category: "Layout & files",
    description: "Communicate status through compact semantic labels.",
    api: null,
    exports: ["Badge"],
    props: [
      {
        name: "variant",
        type: "success | warning | neutral | info | danger",
        description: "Semantic appearance.",
      },
    ],
    alpha: false,
  },
  {
    slug: "breadcrumbs",
    name: "Breadcrumbs",
    category: "Navigation",
    description: "Show a page’s position within a hierarchy.",
    api: "Breadcrumbs",
    exports: ["Breadcrumbs", "Breadcrumb"],
    props: [
      {
        name: "items",
        type: "Iterable<T>",
        description: "Items for a dynamic collection.",
      },
    ],
    alpha: false,
  },
  {
    slug: "button",
    name: "Button",
    category: "Actions",
    description: "Trigger an action with a clear, tactile press.",
    api: "Button",
    exports: ["Button"],
    props: [
      {
        name: "variant",
        type: "primary | secondary | ghost",
        description: "Visual emphasis.",
      },
      {
        name: "isDisabled",
        type: "boolean",
        description: "Prevent interaction.",
      },
      {
        name: "onPress",
        type: "(event) => void",
        description: "Handle pointer and keyboard activation.",
      },
    ],
    alpha: false,
  },
  {
    slug: "calendar",
    name: "Calendar",
    category: "Date & time",
    description: "Select a date from a localized calendar.",
    api: "Calendar",
    exports: [
      "Calendar",
      "CalendarGrid",
      "CalendarGridHeader",
      "CalendarHeaderCell",
      "CalendarGridBody",
      "CalendarCell",
    ],
    props: [
      {
        name: "value / defaultValue",
        type: "DateValue",
        description:
          "Controlled or initial value from @internationalized/date.",
      },
      {
        name: "onChange",
        type: "(value) => void",
        description: "Respond to edits or selection.",
      },
      {
        name: "isDisabled / isReadOnly",
        type: "boolean",
        description: "Control editing availability.",
      },
    ],
    alpha: false,
  },
  {
    slug: "card",
    name: "Card",
    category: "Layout & files",
    description: "Give related content a softly raised surface.",
    api: null,
    exports: ["Card"],
    props: [
      {
        name: "children",
        type: "ReactNode",
        description: "Card content.",
      },
      {
        name: "className",
        type: "string",
        description: "Customize the surface.",
      },
    ],
    alpha: false,
  },
  {
    slug: "checkbox",
    name: "Checkbox",
    category: "Forms",
    description: "Choose one or more independent options.",
    api: "Checkbox",
    exports: ["Checkbox"],
    props: [
      {
        name: "isSelected / defaultSelected",
        type: "boolean",
        description: "Controlled or initial selection.",
      },
      {
        name: "onChange",
        type: "(selected: boolean) => void",
        description: "Respond to selection.",
      },
      {
        name: "isIndeterminate",
        type: "boolean",
        description: "Represent partial selection.",
      },
    ],
    alpha: false,
  },
  {
    slug: "checkbox-group",
    name: "Checkbox Group",
    category: "Forms",
    description: "Organize related checkboxes under a shared label.",
    api: "CheckboxGroup",
    exports: ["CheckboxGroup"],
    props: [
      {
        name: "value / defaultValue",
        type: "string[]",
        description: "Selected checkbox values.",
      },
      {
        name: "onChange",
        type: "(value: string[]) => void",
        description: "Respond to selection.",
      },
    ],
    alpha: false,
  },
  {
    slug: "color-area",
    name: "Color Area",
    category: "Color",
    description: "Adjust two color channels on a two-dimensional surface.",
    api: "ColorArea",
    exports: ["ColorArea", "ColorThumb"],
    props: [
      {
        name: "xChannel / yChannel",
        type: "ColorChannel",
        description: "Channels represented by each axis.",
      },
      {
        name: "colorSpace",
        type: "ColorSpace",
        description: "Color model used for adjustment.",
      },
    ],
    alpha: false,
  },
  {
    slug: "color-field",
    name: "Color Field",
    category: "Color",
    description: "Enter and validate a color value.",
    api: "ColorField",
    exports: ["ColorField", "Input"],
    props: [
      {
        name: "value / defaultValue",
        type: "Color | string",
        description: "Controlled or initial color.",
      },
      {
        name: "onChange",
        type: "(color: Color | null) => void",
        description: "Respond to a valid color.",
      },
    ],
    alpha: false,
  },
  {
    slug: "color-picker",
    name: "Color Picker",
    category: "Color",
    description: "Share color state across multiple color controls.",
    api: "ColorPicker",
    exports: ["ColorPicker"],
    props: [
      {
        name: "value / defaultValue",
        type: "Color | string",
        description: "Shared color state.",
      },
      {
        name: "onChange",
        type: "(color) => void",
        description: "Respond to changes in any child control.",
      },
    ],
    alpha: false,
  },
  {
    slug: "color-slider",
    name: "Color Slider",
    category: "Color",
    description: "Adjust a single color channel.",
    api: "ColorSlider",
    exports: ["ColorSlider", "SliderTrack", "ColorThumb"],
    props: [
      {
        name: "channel",
        type: "ColorChannel",
        description: "Channel adjusted by the slider.",
      },
      {
        name: "value / defaultValue",
        type: "Color | string",
        description: "Controlled or initial color.",
      },
    ],
    alpha: false,
  },
  {
    slug: "color-swatch",
    name: "Color Swatch",
    category: "Color",
    description: "Display a color with an accessible description.",
    api: "ColorSwatch",
    exports: ["ColorSwatch"],
    props: [
      {
        name: "color",
        type: "Color | string",
        description: "Color to display.",
      },
    ],
    alpha: false,
  },
  {
    slug: "color-swatch-picker",
    name: "Color Swatch Picker",
    category: "Color",
    description: "Choose a color from a set of swatches.",
    api: "ColorSwatchPicker",
    exports: ["ColorSwatchPicker", "ColorSwatchPickerItem", "ColorSwatch"],
    props: [
      {
        name: "value / defaultValue",
        type: "Color | string",
        description: "Selected color.",
      },
      {
        name: "onChange",
        type: "(color) => void",
        description: "Respond to a new selection.",
      },
    ],
    alpha: false,
  },
  {
    slug: "color-wheel",
    name: "Color Wheel",
    category: "Color",
    description: "Explore hue around a circular color wheel.",
    api: "ColorWheel",
    exports: ["ColorWheel", "ColorWheelTrack", "ColorThumb"],
    props: [
      {
        name: "outerRadius",
        type: "number",
        description: "Outer radius in pixels (required).",
      },
      {
        name: "innerRadius",
        type: "number",
        description: "Inner radius in pixels (required).",
      },
      {
        name: "value / defaultValue",
        type: "Color | string",
        description: "Controlled or initial color.",
      },
    ],
    alpha: false,
  },
  {
    slug: "combo-box",
    name: "Combo Box",
    category: "Collections",
    description: "Combine editable text with a list of suggestions.",
    api: "ComboBox",
    exports: ["ComboBox", "Input", "Popover", "ListBox", "ListBoxItem"],
    props: [
      {
        name: "selectedKey / defaultSelectedKey",
        type: "Key",
        description: "Selected option.",
      },
      {
        name: "inputValue / defaultInputValue",
        type: "string",
        description: "Input text.",
      },
      {
        name: "allowsCustomValue",
        type: "boolean",
        description: "Allow values outside the collection.",
      },
    ],
    alpha: false,
  },
  {
    slug: "date-field",
    name: "Date Field",
    category: "Date & time",
    description: "Edit a date through localized, keyboard-accessible segments.",
    api: "DateField",
    exports: ["DateField", "DateInput", "DateSegment"],
    props: [
      {
        name: "value / defaultValue",
        type: "DateValue",
        description:
          "Controlled or initial value from @internationalized/date.",
      },
      {
        name: "onChange",
        type: "(value) => void",
        description: "Respond to edits or selection.",
      },
      {
        name: "isDisabled / isReadOnly",
        type: "boolean",
        description: "Control editing availability.",
      },
    ],
    alpha: false,
  },
  {
    slug: "date-picker",
    name: "Date Picker",
    category: "Date & time",
    description: "Combine a segmented date field with a calendar popover.",
    api: "DatePicker",
    exports: ["DatePicker", "DateInput", "DateSegment"],
    props: [
      {
        name: "value / defaultValue",
        type: "DateValue",
        description:
          "Controlled or initial value from @internationalized/date.",
      },
      {
        name: "onChange",
        type: "(value) => void",
        description: "Respond to edits or selection.",
      },
      {
        name: "isDisabled / isReadOnly",
        type: "boolean",
        description: "Control editing availability.",
      },
    ],
    alpha: false,
  },
  {
    slug: "date-range-picker",
    name: "Date Range Picker",
    category: "Date & time",
    description: "Choose a date range through fields or a calendar.",
    api: "DateRangePicker",
    exports: ["DateRangePicker", "DateInput", "DateSegment"],
    props: [
      {
        name: "value / defaultValue",
        type: "RangeValue<DateValue>",
        description:
          "Controlled or initial value from @internationalized/date.",
      },
      {
        name: "onChange",
        type: "(value) => void",
        description: "Respond to edits or selection.",
      },
      {
        name: "isDisabled / isReadOnly",
        type: "boolean",
        description: "Control editing availability.",
      },
    ],
    alpha: false,
  },
  {
    slug: "dialog",
    name: "Dialog",
    category: "Overlays",
    description: "Focus on an important task with an animated dialog.",
    api: "Dialog",
    exports: ["AnimatedOverlay", "AnimatedModal"],
    props: [
      {
        name: "isOpen",
        type: "boolean",
        description: "Control AnimatedOverlay visibility.",
      },
      {
        name: "onOpenChange",
        type: "(open: boolean) => void",
        description: "Synchronize dismissal.",
      },
      {
        name: "children",
        type: "ReactNode",
        description: "Place AnimatedModal and Dialog inside the overlay.",
      },
    ],
    alpha: false,
  },
  {
    slug: "disclosure",
    name: "Disclosure",
    category: "Navigation",
    description: "Expand and collapse a section of content.",
    api: "Disclosure",
    exports: ["Disclosure", "DisclosurePanel"],
    props: [
      {
        name: "isExpanded / defaultExpanded",
        type: "boolean",
        description: "Controlled or initial expansion.",
      },
      {
        name: "onExpandedChange",
        type: "(expanded) => void",
        description: "Respond to expansion.",
      },
    ],
    alpha: false,
  },
  {
    slug: "disclosure-group",
    name: "Disclosure Group",
    category: "Navigation",
    description: "Coordinate a group of expandable sections.",
    api: "DisclosureGroup",
    exports: ["DisclosureGroup", "Disclosure", "DisclosurePanel"],
    props: [
      {
        name: "expandedKeys / defaultExpandedKeys",
        type: "Iterable<Key>",
        description: "Expanded disclosures.",
      },
      {
        name: "allowsMultipleExpanded",
        type: "boolean",
        description: "Allow multiple open sections.",
      },
    ],
    alpha: false,
  },
  {
    slug: "drop-zone",
    name: "Drop Zone",
    category: "Layout & files",
    description: "Accept files through drag and drop or a file picker.",
    api: "DropZone",
    exports: ["DropZone"],
    props: [
      {
        name: "onDrop",
        type: "(event) => void",
        description: "Read dropped items.",
      },
      {
        name: "isDisabled",
        type: "boolean",
        description: "Disable dropping.",
      },
    ],
    alpha: false,
  },
  {
    slug: "file-trigger",
    name: "File Trigger",
    category: "Layout & files",
    description: "Open the native file picker from an accessible trigger.",
    api: "FileTrigger",
    exports: ["FileTrigger"],
    props: [
      {
        name: "acceptedFileTypes",
        type: "string[]",
        description: "Accepted MIME types or extensions.",
      },
      {
        name: "allowsMultiple",
        type: "boolean",
        description: "Allow more than one file.",
      },
      {
        name: "onSelect",
        type: "(files: FileList | null) => void",
        description: "Read the selected files.",
      },
    ],
    alpha: false,
  },
  {
    slug: "form",
    name: "Form",
    category: "Forms",
    description: "Collect values with native validation and accessible errors.",
    api: "Form",
    exports: ["Form"],
    props: [
      {
        name: "onSubmit",
        type: "FormEventHandler",
        description: "Handle valid submission.",
      },
      {
        name: "validationErrors",
        type: "ValidationErrors",
        description: "Provide server-side errors.",
      },
    ],
    alpha: false,
  },
  {
    slug: "grid-list",
    name: "Grid List",
    category: "Collections",
    description: "Navigate and select rich collection items.",
    api: "GridList",
    exports: ["GridList", "GridListItem"],
    props: [
      {
        name: "selectionMode",
        type: "none | single | multiple",
        description: "Selection behavior.",
      },
      {
        name: "selectedKeys / defaultSelectedKeys",
        type: 'Iterable<Key> | "all"',
        description: "Controlled or initial selection.",
      },
      {
        name: "onSelectionChange",
        type: "(keys) => void",
        description: "Respond to selection.",
      },
    ],
    alpha: false,
  },
  {
    slug: "group",
    name: "Group",
    category: "Forms",
    description: "Group related controls and their focus states.",
    api: "Group",
    exports: ["Group"],
    props: [
      {
        name: "isDisabled",
        type: "boolean",
        description: "Propagate disabled state to supported controls.",
      },
      {
        name: "aria-label",
        type: "string",
        description: "Accessible group name.",
      },
    ],
    alpha: false,
  },
  {
    slug: "input",
    name: "Input",
    category: "Forms",
    description: "A recessed input primitive for composing accessible fields.",
    api: "Input",
    exports: ["Input"],
    props: [
      {
        name: "value / defaultValue",
        type: "string",
        description: "Controlled or initial text.",
      },
      {
        name: "onChange",
        type: "ChangeEventHandler",
        description: "Handle the input event.",
      },
      {
        name: "disabled",
        type: "boolean",
        description: "Disable the native input.",
      },
    ],
    alpha: false,
  },
  {
    slug: "label",
    name: "Label",
    category: "Forms",
    description: "Associate a visible name with its control.",
    api: "Label",
    exports: ["Label"],
    props: [
      {
        name: "htmlFor",
        type: "string",
        description: "ID of the associated control.",
      },
    ],
    alpha: false,
  },
  {
    slug: "link",
    name: "Link",
    category: "Actions",
    description: "Navigate to another page or destination.",
    api: "Link",
    exports: ["Link"],
    props: [
      {
        name: "href",
        type: "string",
        description: "Link destination.",
      },
      {
        name: "isDisabled",
        type: "boolean",
        description: "Prevent activation.",
      },
    ],
    alpha: false,
  },
  {
    slug: "list-box",
    name: "List Box",
    category: "Collections",
    description: "Select one or more options from a keyboard-navigable list.",
    api: "ListBox",
    exports: ["ListBox", "ListBoxItem", "ListBoxSection", "Header"],
    props: [
      {
        name: "selectionMode",
        type: "none | single | multiple",
        description: "Selection behavior.",
      },
      {
        name: "selectedKeys / defaultSelectedKeys",
        type: 'Iterable<Key> | "all"',
        description: "Controlled or initial selection.",
      },
      {
        name: "onSelectionChange",
        type: "(keys) => void",
        description: "Respond to selection.",
      },
    ],
    alpha: false,
  },
  {
    slug: "menu",
    name: "Menu",
    category: "Collections",
    description: "Expose contextual actions in a focused popover.",
    api: "Menu",
    exports: ["Menu", "MenuItem", "MenuSection", "Header"],
    props: [
      {
        name: "onAction",
        type: "(key: Key) => void",
        description: "Handle menu action.",
      },
      {
        name: "disabledKeys",
        type: "Iterable<Key>",
        description: "Disable specific items.",
      },
    ],
    alpha: false,
  },
  {
    slug: "meter",
    name: "Meter",
    category: "Feedback",
    description: "Display a measurement within a known range.",
    api: "Meter",
    exports: ["Meter"],
    props: [
      {
        name: "value",
        type: "number",
        description: "Current value.",
      },
      {
        name: "minValue / maxValue",
        type: "number",
        description: "Valid range.",
      },
    ],
    alpha: false,
  },
  {
    slug: "modal",
    name: "Modal",
    category: "Overlays",
    description: "Present a dialog with a backdrop and contained focus.",
    api: "Modal",
    exports: ["ModalOverlay", "Modal"],
    props: [
      {
        name: "isOpen / defaultOpen",
        type: "boolean",
        description: "Control ModalOverlay visibility.",
      },
      {
        name: "isDismissable",
        type: "boolean",
        description: "Allow outside-click dismissal.",
      },
    ],
    alpha: false,
  },
  {
    slug: "navigation-tree",
    name: "Navigation Tree",
    category: "Collections",
    description: "Navigate a hierarchy of destinations.",
    api: "NavigationTree",
    exports: [
      "NavigationTree",
      "NavigationTreeItem",
      "NavigationTreeSection",
      "NavigationTreeHeader",
    ],
    props: [
      {
        name: "selectedRoute",
        type: "string | null",
        description: "Current destination.",
      },
      {
        name: "expandedKeys / defaultExpandedKeys",
        type: "Iterable<Key>",
        description: "Expanded branches.",
      },
    ],
    alpha: false,
  },
  {
    slug: "number-field",
    name: "Number Field",
    category: "Forms",
    description: "Adjust numeric values with accessible increment controls.",
    api: "NumberField",
    exports: ["NumberField", "Input"],
    props: [
      {
        name: "value",
        type: "number",
        description: "Current value.",
      },
      {
        name: "minValue / maxValue",
        type: "number",
        description: "Valid range.",
      },
      {
        name: "onChange",
        type: "(value) => void",
        description: "Respond to value changes.",
      },
    ],
    alpha: false,
  },
  {
    slug: "popover",
    name: "Popover",
    category: "Overlays",
    description: "Anchor contextual content to a trigger.",
    api: "Popover",
    exports: ["Popover", "OverlayArrow"],
    props: [
      {
        name: "placement",
        type: "Placement",
        description: "Position relative to the trigger.",
      },
      {
        name: "isOpen / defaultOpen",
        type: "boolean",
        description: "Control visibility.",
      },
      {
        name: "offset",
        type: "number",
        description: "Distance from the trigger.",
      },
    ],
    alpha: false,
  },
  {
    slug: "preview-trigger",
    name: "Preview Trigger",
    category: "Overlays",
    description: "Preview related content on hover or keyboard focus.",
    api: "PreviewTrigger",
    exports: ["PreviewTrigger"],
    props: [
      {
        name: "delay",
        type: "number",
        description: "Hover delay before opening.",
      },
      {
        name: "closeDelay",
        type: "number",
        description: "Delay before closing the preview.",
      },
    ],
    alpha: false,
  },
  {
    slug: "progress-bar",
    name: "Progress Bar",
    category: "Feedback",
    description: "Communicate progress toward completing a task.",
    api: "ProgressBar",
    exports: ["ProgressBar"],
    props: [
      {
        name: "value",
        type: "number",
        description: "Current value.",
      },
      {
        name: "minValue / maxValue",
        type: "number",
        description: "Valid range.",
      },
    ],
    alpha: false,
  },
  {
    slug: "radio-group",
    name: "Radio Group",
    category: "Forms",
    description: "Choose one option from a labeled group.",
    api: "RadioGroup",
    exports: ["RadioGroup", "Radio"],
    props: [
      {
        name: "value / defaultValue",
        type: "string",
        description: "Selected radio value.",
      },
      {
        name: "onChange",
        type: "(value: string) => void",
        description: "Respond to selection.",
      },
    ],
    alpha: false,
  },
  {
    slug: "range-calendar",
    name: "Range Calendar",
    category: "Date & time",
    description: "Select the start and end of a date range.",
    api: "RangeCalendar",
    exports: [
      "RangeCalendar",
      "CalendarGrid",
      "CalendarGridHeader",
      "CalendarHeaderCell",
      "CalendarGridBody",
      "CalendarCell",
    ],
    props: [
      {
        name: "value / defaultValue",
        type: "RangeValue<DateValue>",
        description:
          "Controlled or initial value from @internationalized/date.",
      },
      {
        name: "onChange",
        type: "(value) => void",
        description: "Respond to edits or selection.",
      },
      {
        name: "isDisabled / isReadOnly",
        type: "boolean",
        description: "Control editing availability.",
      },
    ],
    alpha: false,
  },
  {
    slug: "search-field",
    name: "Search Field",
    category: "Forms",
    description: "Enter and clear a search query.",
    api: "SearchField",
    exports: ["SearchField", "Input"],
    props: [
      {
        name: "value / defaultValue",
        type: "string",
        description: "Controlled or initial text.",
      },
      {
        name: "onChange",
        type: "(value: string) => void",
        description: "Respond to text changes on the parent field.",
      },
      {
        name: "isRequired / isDisabled",
        type: "boolean",
        description: "Validation and availability on the parent field.",
      },
    ],
    alpha: false,
  },
  {
    slug: "select",
    name: "Select",
    category: "Collections",
    description: "Choose an option from a popover list.",
    api: "Select",
    exports: ["Select"],
    props: [
      {
        name: "label",
        type: "string",
        description: "Visible label.",
      },
      {
        name: "options",
        type: "{ id: string; label: string }[]",
        description: "Available options.",
      },
      {
        name: "selectedKey / defaultSelectedKey",
        type: "Key",
        description: "Controlled or initial selection.",
      },
      {
        name: "onSelectionChange",
        type: "(key) => void",
        description: "Respond to selection.",
      },
    ],
    alpha: false,
  },
  {
    slug: "separator",
    name: "Separator",
    category: "Layout & files",
    description: "Visually and semantically divide related content.",
    api: "Separator",
    exports: ["Separator"],
    props: [
      {
        name: "orientation",
        type: "horizontal | vertical",
        description: "Direction of the separator.",
      },
    ],
    alpha: false,
  },
  {
    slug: "slider",
    name: "Slider",
    category: "Forms",
    description: "Adjust a value by dragging or using arrow keys.",
    api: "Slider",
    exports: [
      "Slider",
      "SliderOutput",
      "SliderTrack",
      "SliderFill",
      "SliderThumb",
    ],
    props: [
      {
        name: "value",
        type: "number | number[]",
        description: "Current value.",
      },
      {
        name: "minValue / maxValue",
        type: "number",
        description: "Valid range.",
      },
      {
        name: "onChange",
        type: "(value) => void",
        description: "Respond to value changes.",
      },
    ],
    alpha: false,
  },
  {
    slug: "switch",
    name: "Switch",
    category: "Forms",
    description: "Turn a setting on or off.",
    api: "Switch",
    exports: ["Switch"],
    props: [
      {
        name: "isSelected / defaultSelected",
        type: "boolean",
        description: "Controlled or initial state.",
      },
      {
        name: "onChange",
        type: "(selected: boolean) => void",
        description: "Respond to a state change.",
      },
    ],
    alpha: false,
  },
  {
    slug: "table",
    name: "Table",
    category: "Collections",
    description:
      "Organize tabular data with row selection and keyboard navigation.",
    api: "Table",
    exports: ["Table", "TableHeader", "Column", "TableBody", "Row", "Cell"],
    props: [
      {
        name: "selectionMode",
        type: "none | single | multiple",
        description: "Selection behavior.",
      },
      {
        name: "selectedKeys / defaultSelectedKeys",
        type: 'Iterable<Key> | "all"',
        description: "Controlled or initial selection.",
      },
      {
        name: "onSelectionChange",
        type: "(keys) => void",
        description: "Respond to selection.",
      },
    ],
    alpha: false,
  },
  {
    slug: "tabs",
    name: "Tabs",
    category: "Navigation",
    description: "Switch between related panels of content.",
    api: "Tabs",
    exports: ["Tabs", "TabList", "Tab", "TabPanel"],
    props: [
      {
        name: "selectedKey / defaultSelectedKey",
        type: "Key",
        description: "Active panel.",
      },
      {
        name: "keyboardActivation",
        type: "automatic | manual",
        description: "When keyboard navigation activates a tab.",
      },
    ],
    alpha: false,
  },
  {
    slug: "tag-group",
    name: "Tag Group",
    category: "Collections",
    description: "Display and remove a collection of compact tags.",
    api: "TagGroup",
    exports: ["TagGroup", "TagList", "Tag"],
    props: [
      {
        name: "onRemove",
        type: "(keys: Set<Key>) => void",
        description: "Remove tags from your data.",
      },
      {
        name: "isDisabled",
        type: "boolean",
        description: "Disable interactions.",
      },
    ],
    alpha: false,
  },
  {
    slug: "text-area",
    name: "Text Area",
    category: "Forms",
    description: "Make room for longer messages and descriptions.",
    api: "TextArea",
    exports: ["TextArea"],
    props: [
      {
        name: "value / defaultValue",
        type: "string",
        description: "Controlled or initial text.",
      },
      {
        name: "onChange",
        type: "(value: string) => void",
        description: "Respond to text changes on the parent field.",
      },
      {
        name: "isRequired / isDisabled",
        type: "boolean",
        description: "Validation and availability on the parent field.",
      },
    ],
    alpha: false,
  },
  {
    slug: "text-field",
    name: "Text Field",
    category: "Forms",
    description:
      "A labeled text input with validation and helpful descriptions.",
    api: "TextField",
    exports: ["TextField"],
    props: [
      {
        name: "label",
        type: "string",
        description: "Visible accessible label.",
      },
      {
        name: "value / defaultValue",
        type: "string",
        description: "Controlled or initial text.",
      },
      {
        name: "onChange",
        type: "(value: string) => void",
        description: "Respond to text changes on the parent field.",
      },
      {
        name: "isRequired / isDisabled",
        type: "boolean",
        description: "Validation and availability on the parent field.",
      },
    ],
    alpha: false,
  },
  {
    slug: "time-field",
    name: "Time Field",
    category: "Date & time",
    description: "Enter a time using localized segments.",
    api: "TimeField",
    exports: ["TimeField", "DateInput", "DateSegment"],
    props: [
      {
        name: "value / defaultValue",
        type: "TimeValue",
        description:
          "Controlled or initial value from @internationalized/date.",
      },
      {
        name: "onChange",
        type: "(value) => void",
        description: "Respond to edits or selection.",
      },
      {
        name: "isDisabled / isReadOnly",
        type: "boolean",
        description: "Control editing availability.",
      },
    ],
    alpha: false,
  },
  {
    slug: "toast",
    name: "Toast",
    category: "Feedback",
    description: "Announce transient feedback without interrupting a task.",
    api: "Toast",
    exports: ["ToastRegion", "Toast", "ToastContent"],
    props: [
      {
        name: "queue",
        type: "ToastQueue<T>",
        description: "Queue passed to ToastRegion.",
      },
      {
        name: "toast",
        type: "QueuedToast<T>",
        description: "Toast data supplied by the region render function.",
      },
    ],
    alpha: true,
  },
  {
    slug: "toggle-button",
    name: "Toggle Button",
    category: "Actions",
    description: "Toggle an action between pressed and unpressed states.",
    api: "ToggleButton",
    exports: ["ToggleButton"],
    props: [
      {
        name: "isSelected / defaultSelected",
        type: "boolean",
        description: "Pressed state.",
      },
      {
        name: "onChange",
        type: "(selected: boolean) => void",
        description: "Respond to presses.",
      },
    ],
    alpha: false,
  },
  {
    slug: "toggle-button-group",
    name: "Toggle Button Group",
    category: "Actions",
    description: "Coordinate single or multiple toggle selections.",
    api: "ToggleButtonGroup",
    exports: ["ToggleButtonGroup", "ToggleButton"],
    props: [
      {
        name: "selectionMode",
        type: "single | multiple",
        description: "Selection behavior.",
      },
      {
        name: "selectedKeys / defaultSelectedKeys",
        type: "Iterable<Key>",
        description: "Pressed buttons.",
      },
    ],
    alpha: false,
  },
  {
    slug: "token-field",
    name: "Token Field",
    category: "Forms",
    description: "Edit text with inline, keyboard-accessible tokens.",
    api: "TokenField",
    exports: ["TokenField", "TokenInput", "Token"],
    props: [
      {
        name: "value / defaultValue",
        type: "TokenFieldValue",
        description: "Text and token segments.",
      },
      {
        name: "onChange",
        type: "(value: TokenFieldValue) => void",
        description: "Respond to edits.",
      },
    ],
    alpha: false,
  },
  {
    slug: "toolbar",
    name: "Toolbar",
    category: "Actions",
    description: "Group actions with efficient arrow-key navigation.",
    api: "Toolbar",
    exports: ["Toolbar"],
    props: [
      {
        name: "orientation",
        type: "horizontal | vertical",
        description: "Direction of arrow-key navigation.",
      },
      {
        name: "aria-label",
        type: "string",
        description: "Accessible toolbar name.",
      },
    ],
    alpha: false,
  },
  {
    slug: "tooltip",
    name: "Tooltip",
    category: "Overlays",
    description: "Reveal a short description on hover or focus.",
    api: "Tooltip",
    exports: ["Tooltip"],
    props: [
      {
        name: "content",
        type: "ReactNode",
        description: "Accessible tooltip content.",
      },
      {
        name: "children",
        type: "ReactNode",
        description: "Focusable trigger.",
      },
    ],
    alpha: false,
  },
  {
    slug: "tree",
    name: "Tree",
    category: "Collections",
    description: "Explore hierarchical items with keyboard navigation.",
    api: "Tree",
    exports: ["Tree", "TreeItem", "TreeSection", "TreeHeader"],
    props: [
      {
        name: "selectionMode",
        type: "none | single | multiple",
        description: "Selection behavior.",
      },
      {
        name: "selectedKeys / defaultSelectedKeys",
        type: 'Iterable<Key> | "all"',
        description: "Controlled or initial selection.",
      },
      {
        name: "onSelectionChange",
        type: "(keys) => void",
        description: "Respond to selection.",
      },
    ],
    alpha: false,
  },
  {
    slug: "virtualizer",
    name: "Virtualizer",
    category: "Collections",
    description: "Render visible items efficiently in large collections.",
    api: "Virtualizer",
    exports: ["Virtualizer"],
    props: [
      {
        name: "layout",
        type: "Layout | constructor",
        description:
          "Choose ListLayout, GridLayout, TableLayout or WaterfallLayout.",
      },
      {
        name: "layoutOptions",
        type: "object",
        description: "Configure row size and other layout dimensions.",
      },
    ],
    alpha: false,
  },
] as const;
export type ComponentEntry = (typeof catalog)[number];
export const componentCategories = [
  "Actions",
  "Forms",
  "Collections",
  "Date & time",
  "Color",
  "Overlays",
  "Navigation",
  "Feedback",
  "Layout & files",
];
